version: '3.8'

services:
  backend:
    build: .
    container_name: fleet-backend
    restart: unless-stopped
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - NODE_ENV=production
      - CORS_ORIGIN=*
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=10485760
      - RATE_LIMIT_WINDOW=900000
      - RATE_LIMIT_MAX=100
    volumes:
      - ./uploads:/app/uploads
    networks:
      - fleet-network

  nginx:
    image: nginx:alpine
    container_name: fleet-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - backend
    networks:
      - fleet-network

networks:
  fleet-network:
    driver: bridge 